//DEFINES .h
#define  READBIT(WORD,POS)      ((WORD>>POS)&1)
#define WRITEBIT(WORD,POS,BIT)   WORD|= (WORD & ~(1<<POS) | (BIT<<POS))
//#define  WRITEBYTE(WORD,STARTBIT_POS,BYTE)    WORD =  (WORD & ~(0XFF<< STARTBIT_POS)) | (BYTE<<STARTBIT_POS)
#define  READBYTE(WORD,STARTBIT_POS) ((WORD>>STARTBIT_POS) & OXFF)
#define  WRITEBYTE(WORD,BYTE,STARTBIT_POSN)   WORD = (((WORD & ~(0XFF<<STARTBIT_POSN)) | BYTE<<STARTBIT_POSN))
#define WRITENIBBLE(WORD,NIBBLE,STARTBIT_POS)   WORD = ((WORD & ~(15 <<STARTBIT_POS)) | NIBBLE<<STARTBIT_POS)
#define READNIBBLE(WORD,STARTBIT_POS)   ((WORD>>STARTBIT_POS)&0XF)
